name: Update Code::Stats Readme

on:
  schedule:
    # Runs every 6 hours to update your stats
    - cron: '0 */6 * * *'
  # Allows you to run it manually from the Actions tab
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Code::Stats
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out your repository so we can edit the README
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Fetch your public stats from the Code::Stats API
      # This uses a basic tool that is guaranteed to be available.
      - name: Fetch Code::Stats Data
        run: curl -o codestats.json https://codestats.net/api/users/TrevLovesPizza

      # Step 3: Use Python to format the stats and update the README
      # This is the most reliable way to process the data.
      - name: Update README File
        run: |
          import json
          import re

          # Load the stats data
          try:
            with open('codestats.json', 'r') as f:
              stats = json.load(f)
          except (IOError, json.JSONDecodeError):
            print("Could not read or parse codestats.json")
            exit(1)

          # Prepare the formatted markdown string
          new_xp = stats.get('new_xp', 0)
          total_xp = stats.get('total_xp', 0)
          
          top_langs = sorted(stats.get('languages', {}).items(), key=lambda item: item[1].get('xps', 0), reverse=True)[:5]
          
          stats_md = "#### 💻 My Coding Stats\n\n"
          stats_md += f"**Total XP:** {total_xp:,}\n\n"
          stats_md += "**Top Languages:**\n"
          for lang, data in top_langs:
              stats_md += f"- {lang}: {data.get('xps', 0):,} XP\n"

          # Read the README file
          with open('README.md', 'r') as f:
            readme_content = f.read()

          # Replace the content between the markers
          new_readme = re.sub(
            r'(?s)<!-- CODESTATS:START -->.*<!-- CODESTATS:END -->',
            f'<!-- CODESTATS:START -->\n{stats_md}\n<!-- CODESTATS:END -->',
            readme_content
          )

          # Write the new content back to the README
          with open('README.md', 'w') as f:
            f.write(new_readme)
        shell: python

      # Step 4: Commit and push the changes
      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git diff --quiet || (git add README.md && git commit -m "Update Code::Stats" && git push)
