name: Update README with Gist Content

on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get Gist Content
        id: get_gist_content
        uses: andymckay/get-gist-action@master
        with:
          # Use the FULL URL to your public Gist
          gistURL: https://gist.github.com/TrevorBrowning/1ad666e6792dc86bb852cfc2fc8aca73
      
      - name: Update README with Gist content
        uses: jamesravey/replace-between-tags-action@v1.1.0
        with:
          path: README.md
          tags: GIST_STATS
          content: ${{ steps.get_gist_content.outputs.content }}

      - name: Commit and Push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git diff --quiet || (git add README.md && git commit -m "Update Code Stats from Gist" && git push)
