name: Update README with Gist Content

on:
  # This runs the workflow every hour
  schedule:
    - cron: '0 * * * *'
  # This allows you to run it manually from the Actions tab
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      
      - name: Update README with Gist content
        uses: anmol098/readme-gist@master
        with:
          # The ID of your public Gist
          id: YOUR_GIST_ID_HERE

          # Your GitHub Personal Access Token, stored in a repository secret
          token: ${{ secrets.GIST_PAT }}

          # The file in your repository to update
          file: README.md

          # The comment markers in your README file
          comment_start: '<!-- GIST_STATS:START -->'
          comment_end: '<!-- GIST_STATS:END -->'
